"""add financeiro table

Revision ID: 9752c5d55525
Revises: 
Create Date: 2025-02-12 21:13:09.588424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9752c5d55525'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financeiro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imovel_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['imovel_id'], ['imovel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financeiro')
    # ### end Alembic commands ###
