"""add data_cadastro to imovel

Revision ID: bc771d0bdefb
Revises: 9752c5d55525
Create Date: 2025-02-12 21:40:52.238379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc771d0bdefb'
down_revision = '9752c5d55525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imovel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_cadastro', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imovel', schema=None) as batch_op:
        batch_op.drop_column('data_cadastro')

    # ### end Alembic commands ###
